batch_size: 48
betas:
- 0.9
- 0.999
clip_value: 1.0
clipping_gradient: null
cv: true
early_stop: 10
ema_decay: 0.0
eps: 1.0e-08
factor: 0.46
frozen_core: false
gradient_interval: 1
lower_weight: 1.0
lr: 0.000181520024149924
minlr: 1.0e-08
mutual_info_weight: 0.0
nfold: 5
num_epochs: 86
num_sample: 1000
optimizer_choice: adamw
patience: 6
train_ratio: 0.7
upper_weight: 1
val_interval: 2
weight_decay: 0.00031442048071180775
